@Fiap.Cloud.Games.Api_HostAddress = http://localhost:5218

### Gerar Token - Perfil Administrador
POST {{Fiap.Cloud.Games.Api_HostAddress}}/api/auth/
Accept: application/json
Content-Type: application/json

{
  "login": "douglas.loc@hotmail.com",
  "senha": "Doug@123"
}

### Gerar Token - Perfil Usuario
POST {{Fiap.Cloud.Games.Api_HostAddress}}/api/auth/
Accept: application/json
Content-Type: application/json

{
  "login": "victor@hotmail.com",
  "senha": "Victor@123"
}

### Listar Usuários
GET {{Fiap.Cloud.Games.Api_HostAddress}}/api/usuario/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3JAaG90bWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc3VhcmlvIiwianRpIjoiMDBjZmE5ZmItM2M0MS00NmMxLWI5MWItNzNmODRkNDkxMjFhIiwiZXhwIjoxNzg2ODkzMTg2LCJpc3MiOiJGaWFwLkNsb3VkLkdhbWVzIn0.G_KN-BSpTgscmQrVXexLBIVhamcbtW8CpBerKJVtBCU

### Listar Jogos
GET {{Fiap.Cloud.Games.Api_HostAddress}}/api/jogo/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3JAaG90bWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc3VhcmlvIiwianRpIjoiMDBjZmE5ZmItM2M0MS00NmMxLWI5MWItNzNmODRkNDkxMjFhIiwiZXhwIjoxNzg2ODkzMTg2LCJpc3MiOiJGaWFwLkNsb3VkLkdhbWVzIn0.G_KN-BSpTgscmQrVXexLBIVhamcbtW8CpBerKJVtBCU
